import type { Product } from '@/types';

export const categories = [
  { id: 'all', name: 'All' },
  { id: 'hz-collection', name: 'HZ Collection' },
  { id: 'agbada', name: 'Agbada' },
  { id: 'kaftan', name: 'Kaftan' },
  { id: 'casual', name: 'Casual' },
  { id: 'african-culture', name: 'New African culture style' },
];

export const allProducts: Product[] = [
  {
    id: 'hz-shirt',
    name: 'HZ Shirt & Signature Set',
    price: 20000,
    image: 'images/hz-shirt-1.jpg',
    images: ['images/hz-shirt-1.jpg', 'images/hz-new-1.jpeg'],
    category: 'hz-collection',
    description: 'A premium, well-tailored contemporary African-inspired shirt and signature set for the modern man.',
    fabric: 'Luxury Premium Cotton & Viscose',
    fit: 'Contemporary Fit',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Cream', 'White', 'Black'],
    inStock: true,
  },
  // HZ Collection (New)
  {
    id: 'hz-new-2',
    name: 'HZ Urban Tunic',
    price: 35000,
    image: 'images/hz-new-2.jpeg',
    category: 'hz-collection',
    description: 'Minimalist HZ Urban Tunic for everyday luxury.',
    fabric: 'Cotton Mix',
    fit: 'Relaxed Fit',
    care: 'Hand Wash Cold',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Various'],
    inStock: true,
  },
  {
    id: 'hz-new-3',
    name: 'HZ Elite Polo',
    price: 40000,
    image: 'images/hz-new-3.jpeg',
    category: 'hz-collection',
    description: 'Sophisticated HZ Elite Polo with cultural detailing.',
    fabric: 'Premium Pique Cotton',
    fit: 'Slim Fit',
    care: 'Machine Wash Gentle',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Various'],
    inStock: true,
  },
  {
    id: 'hz-new-4',
    name: 'HZ Heritage Shirt',
    price: 48000,
    image: 'images/hz-new-4.jpeg',
    category: 'hz-collection',
    description: 'Timeless HZ Heritage Shirt featuring traditional patterns.',
    fabric: 'Fine Cotton',
    fit: 'Regular Fit',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Various'],
    inStock: true,
  },
  // Agbada Collection
  {
    id: 'agbada-1',
    name: 'Luxe Agbada 1',
    price: 60000,
    image: 'images/agbada-1.jpeg',
    images: ['images/agbada-1.jpeg', 'images/agbada-2.jpeg'],
    category: 'agbada' as const,
    description: 'A grand and majestic Agbada set for high-profile occasions, now available in multiple premium variations.',
    fabric: 'Hand-woven Aso-oke / Premium Silk',
    fit: 'Traditional Grand Fit',
    care: 'Dry Clean Only',
    sizes: ['One Size (Adjustable)'],
    colors: ['Traditional'],
    inStock: true,
  },
  {
    id: 'agbada-4',
    name: 'Green Agbada',
    price: 55000,
    image: 'images/agbada-4.jpeg',
    category: 'agbada' as const,
    description: 'A grand and majestic Agbada set for high-profile occasions in a stunning green shade.',
    fabric: 'Hand-woven Aso-oke / Premium Silk',
    fit: 'Traditional Grand Fit',
    care: 'Dry Clean Only',
    sizes: ['One Size (Adjustable)'],
    colors: ['Green'],
    inStock: true,
  },
  {
    id: 'agbada-6',
    name: 'Green Agbada with Embroidery',
    price: 100000,
    image: 'images/agbada-6.jpeg',
    images: ['images/agbada-6.jpeg', 'images/agbada-5.jpeg'],
    category: 'agbada' as const,
    description: 'A grand and majestic Agbada set for high-profile occasions, featuring contrasting premium textures and intricate embroidery.',
    fabric: 'Hand-woven Aso-oke / Premium Silk',
    fit: 'Traditional Grand Fit',
    care: 'Dry Clean Only',
    sizes: ['One Size (Adjustable)'],
    colors: ['Green with Embroidery'],
    inStock: true,
  },
  {
    id: 'agbada-7',
    name: 'Luxe Agbada 7',
    price: 210000,
    image: 'images/agbada-7.jpeg',
    images: ['images/agbada-7.jpeg', 'images/agbada-3.jpeg', 'images/agbada-8.jpeg'],
    category: 'agbada' as const,
    description: 'A grand and majestic Agbada set for high-profile occasions, showcasing the full range of our architectural designs.',
    fabric: 'Hand-woven Aso-oke / Premium Silk',
    fit: 'Traditional Grand Fit',
    care: 'Dry Clean Only',
    sizes: ['One Size (Adjustable)'],
    colors: ['Traditional'],
    inStock: true,
  },
  ...Array.from({ length: 2 }, (_, i) => ({
    id: `agbada-${i + 9}`,
    name: `Luxe Agbada ${i + 9}`,
    price: 230000 + (i * 10000),
    image: `images/agbada-${i + 9}.jpeg`,
    category: 'agbada' as const,
    description: 'A grand and majestic Agbada set for high-profile occasions.',
    fabric: 'Hand-woven Aso-oke / Premium Silk',
    fit: 'Traditional Grand Fit',
    care: 'Dry Clean Only',
    sizes: ['One Size (Adjustable)'],
    colors: ['Traditional'],
    inStock: true,
  })),
  // Kaftan Collection
  {
    id: 'kaftan-1',
    name: 'White with Stone Kaftan',
    price: 45000,
    image: 'images/kaftan-1.jpeg',
    category: 'kaftan' as const,
    description: 'Expertly tailored white kaftan with intricate stone detailing.',
    fabric: 'Super Fine Polish Cotton',
    fit: 'Slim Fit',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White'],
    inStock: true,
  },
  {
    id: 'kaftan-2',
    name: 'Stripe Kaftan',
    price: 40000,
    image: 'images/kaftan-2.jpeg',
    category: 'kaftan' as const,
    description: 'Expertly tailored stripe kaftan for a modern look.',
    fabric: 'Super Fine Polish Cotton',
    fit: 'Slim Fit',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Stripe'],
    inStock: true,
  },
  {
    id: 'kaftan-3',
    name: 'Wine Kaftan',
    price: 40000,
    image: 'images/kaftan-3.jpeg',
    category: 'kaftan' as const,
    description: 'Expertly tailored wine-colored kaftan with elegant finish.',
    fabric: 'Super Fine Polish Cotton',
    fit: 'Slim Fit',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Wine'],
    inStock: true,
  },
  {
    id: 'kaftan-4',
    name: 'Monogram Blue Kaftan',
    price: 60000,
    image: 'images/kaftan-4.jpeg',
    category: 'kaftan' as const,
    description: 'Expertly tailored blue kaftan featuring signature monogram detailing.',
    fabric: 'Super Fine Polish Cotton',
    fit: 'Slim Fit',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Blue'],
    inStock: true,
  },
  ...Array.from({ length: 5 }, (_, i) => ({
    id: `kaftan-${i + 5}`,
    name: `Premium Kaftan ${i + 5}`,
    price: 85000 + (i * 5000),
    image: `images/kaftan-${i + 5}.jpeg`,
    category: 'kaftan' as const,
    description: 'Expertly tailored kaftan with intricate hand-embroidery.',
    fabric: 'Super Fine Polish Cotton',
    fit: 'Slim Fit',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Various'],
    inStock: true,
  })),
  // Casual Collection
  {
    id: 'casual-1',
    name: 'Casual Luxe 1',
    price: 50000,
    image: 'images/casual-1.jpeg',
    category: 'casual' as const,
    description: 'Relaxed yet refined casual wear for the modern gentleman.',
    fabric: 'Breathable Linen-Cotton Blend',
    fit: 'Relaxed Fit',
    care: 'Machine Wash Cold',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Neutral Tones'],
    inStock: true,
  },
  {
    id: 'casual-2',
    name: 'Casual Luxe 2',
    price: 40000,
    image: 'images/casual-2.jpeg',
    category: 'casual' as const,
    description: 'Relaxed yet refined casual wear for the modern gentleman.',
    fabric: 'Breathable Linen-Cotton Blend',
    fit: 'Relaxed Fit',
    care: 'Machine Wash Cold',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Neutral Tones'],
    inStock: true,
  },
  {
    id: 'casual-3',
    name: 'Casual Luxe 3',
    price: 40000,
    image: 'images/casual-3.jpeg',
    category: 'casual' as const,
    description: 'Relaxed yet refined casual wear for the modern gentleman.',
    fabric: 'Breathable Linen-Cotton Blend',
    fit: 'Relaxed Fit',
    care: 'Machine Wash Cold',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Neutral Tones'],
    inStock: true,
  },
  {
    id: 'casual-9',
    name: 'Casual Luxe 9',
    price: 40000,
    image: 'images/casual-9.jpeg',
    images: ['images/casual-9.jpeg', 'images/casual-6.jpeg'],
    category: 'casual' as const,
    description: 'Relaxed yet refined casual wear for the modern gentleman, available in multiple embroidery styles.',
    fabric: 'Breathable Linen-Cotton Blend',
    fit: 'Relaxed Fit',
    care: 'Machine Wash Cold',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Neutral Tones'],
    inStock: true,
  },
  {
    id: 'casual-10',
    name: 'Casual Luxe 10',
    price: 35000,
    image: 'images/casual-10.jpeg',
    images: ['images/casual-10.jpeg', 'images/casual-5.jpeg'],
    category: 'casual' as const,
    description: 'Relaxed yet refined casual wear for the modern gentleman with seasonal color variations.',
    fabric: 'Breathable Linen-Cotton Blend',
    fit: 'Relaxed Fit',
    care: 'Machine Wash Cold',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Neutral Tones'],
    inStock: true,
  },
  {
    id: 'casual-11',
    name: 'Casual Luxe 11',
    price: 45000,
    image: 'images/casual-11.jpeg',
    category: 'casual' as const,
    description: 'Relaxed yet refined casual wear for the modern gentleman.',
    fabric: 'Breathable Linen-Cotton Blend',
    fit: 'Relaxed Fit',
    care: 'Machine Wash Cold',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Neutral Tones'],
    inStock: true,
  },
  {
    id: 'casual-12',
    name: 'Casual Luxe 12',
    price: 40000,
    image: 'images/casual-12.jpeg',
    images: ['images/casual-12.jpeg', 'images/casual-8.jpeg'],
    category: 'casual' as const,
    description: 'Relaxed yet refined casual wear for the modern gentleman featuring signature stitch detailing.',
    fabric: 'Breathable Linen-Cotton Blend',
    fit: 'Relaxed Fit',
    care: 'Machine Wash Cold',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Neutral Tones'],
    inStock: true,
  },
  // African Culture Collection
  {
    id: 'african-1',
    name: 'African Culture Design 1',
    price: 55000,
    image: 'images/african-1.jpeg',
    images: ['images/african-1.jpeg', 'images/african-2.jpeg', 'images/african-3.jpeg'],
    category: 'african-culture' as const,
    description: 'A masterpiece representing the rich heritage and contemporary style of African culture, featuring multiple perspectives of the same exquisite design.',
    fabric: 'Premium Cultural Fabric',
    fit: 'Classic Contemporary',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Traditional Patterns'],
    inStock: true,
  },
  {
    id: 'african-4',
    name: 'African Culture Design 4',
    price: 40000,
    image: 'images/african-4.jpeg',
    category: 'african-culture' as const,
    description: 'A masterpiece representing the rich heritage and contemporary style of African culture.',
    fabric: 'Premium Cultural Fabric',
    fit: 'Classic Contemporary',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Traditional Patterns'],
    inStock: true,
  },
  {
    id: 'african-5',
    name: 'African Culture Design 5',
    price: 40000,
    image: 'images/african-5.jpeg',
    category: 'african-culture' as const,
    description: 'A masterpiece representing the rich heritage and contemporary style of African culture.',
    fabric: 'Premium Cultural Fabric',
    fit: 'Classic Contemporary',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Traditional Patterns'],
    inStock: true,
  },
  {
    id: 'african-6',
    name: 'African Culture Design 6',
    price: 90000,
    image: 'images/african-6.jpeg',
    images: ['images/african-6.jpeg', 'images/african-7.jpeg'],
    category: 'african-culture' as const,
    description: 'A masterpiece representing the rich heritage and contemporary style of African culture, showcasing detailed artisanal craftsmanship.',
    fabric: 'Premium Cultural Fabric',
    fit: 'Classic Contemporary',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Traditional Patterns'],
    inStock: true,
  },
  {
    id: 'african-8',
    name: 'African Culture Design 8',
    price: 100000,
    image: 'images/african-8.jpeg',
    category: 'african-culture' as const,
    description: 'A masterpiece representing the rich heritage and contemporary style of African culture.',
    fabric: 'Premium Cultural Fabric',
    fit: 'Classic Contemporary',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Traditional Patterns'],
    inStock: true,
  },
];

export const featuredProducts = allProducts.filter(p => 
  ['casual-1', 'casual-2', 'casual-3', 'casual-5', 'casual-6'].includes(p.id)
);
