import type { Product } from '@/types';

export const categories = [
  { id: 'all', name: 'All' },
  { id: 'hz-collection', name: 'HZ Collection' },
  { id: 'agbada', name: 'Agbada' },
  { id: 'kaftan', name: 'Kaftan' },
  { id: 'casual', name: 'Casual' },
  { id: 'african-culture', name: 'New African culture style' },
];

export const allProducts: Product[] = [
  {
    id: 'hz-shirt',
    name: 'HZ Shirt',
    price: 45000,
    image: 'images/hz-shirt-1.jpg',
    category: 'hz-collection',
    description: 'A premium, well-tailored contemporary African-inspired shirt for the modern man.',
    fabric: 'Luxury Premium Cotton',
    fit: 'Contemporary Fit',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Cream', 'White', 'Black'],
    inStock: true,
  },
  {
    id: 'boocut-pant',
    name: 'BOOCUT Pant',
    price: 35000,
    image: 'images/hz-collection.jpg',
    category: 'hz-collection',
    description: 'Perfectly tailored black bootcut trousers, designed for elegance and comfort.',
    fabric: 'Premium Wool Blend',
    fit: 'Bootcut',
    care: 'Dry Clean Only',
    sizes: ['30', '32', '34', '36', '38'],
    colors: ['Black', 'Navy'],
    inStock: true,
  },
  // HZ Collection (New)
  {
    id: 'hz-new-1',
    name: 'HZ Signature Set',
    price: 65000,
    image: 'images/hz-new-1.jpeg',
    category: 'hz-collection',
    description: 'Modern HZ Signature set with a contemporary twist on traditional wear.',
    fabric: 'Premium Viscose',
    fit: 'Regular Fit',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Various'],
    inStock: true,
  },
  {
    id: 'hz-new-2',
    name: 'HZ Urban Tunic',
    price: 55000,
    image: 'images/hz-new-2.jpeg',
    category: 'hz-collection',
    description: 'Minimalist HZ Urban Tunic for everyday luxury.',
    fabric: 'Cotton Mix',
    fit: 'Relaxed Fit',
    care: 'Hand Wash Cold',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Various'],
    inStock: true,
  },
  {
    id: 'hz-new-3',
    name: 'HZ Elite Polo',
    price: 40000,
    image: 'images/hz-new-3.jpeg',
    category: 'hz-collection',
    description: 'Sophisticated HZ Elite Polo with cultural detailing.',
    fabric: 'Premium Pique Cotton',
    fit: 'Slim Fit',
    care: 'Machine Wash Gentle',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Various'],
    inStock: true,
  },
  {
    id: 'hz-new-4',
    name: 'HZ Heritage Shirt',
    price: 48000,
    image: 'images/hz-new-4.jpeg',
    category: 'hz-collection',
    description: 'Timeless HZ Heritage Shirt featuring traditional patterns.',
    fabric: 'Fine Cotton',
    fit: 'Regular Fit',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Various'],
    inStock: true,
  },
  // Agbada Collection
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `agbada-${i + 1}`,
    name: `Luxe Agbada ${i + 1}`,
    price: 150000 + (i * 10000),
    image: `images/agbada-${i + 1}.jpeg`,
    category: 'agbada' as const,
    description: 'A grand and majestic Agbada set for high-profile occasions.',
    fabric: 'Hand-woven Aso-oke / Premium Silk',
    fit: 'Traditional Grand Fit',
    care: 'Dry Clean Only',
    sizes: ['One Size (Adjustable)'],
    colors: ['Traditional'],
    inStock: true,
  })),
  // Kaftan Collection
  ...Array.from({ length: 9 }, (_, i) => ({
    id: `kaftan-${i + 1}`,
    name: `Premium Kaftan ${i + 1}`,
    price: 80000 + (i * 5000),
    image: `images/kaftan-${i + 1}.jpeg`,
    category: 'kaftan' as const,
    description: 'Expertly tailored kaftan with intricate hand-embroidery.',
    fabric: 'Super Fine Polish Cotton',
    fit: 'Slim Fit',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Various'],
    inStock: true,
  })),
  // Casual Collection
  ...Array.from({ length: 12 }, (_, i) => ({
    id: `casual-${i + 1}`,
    name: `Casual Luxe ${i + 1}`,
    price: 45000 + (i * 2000),
    image: `images/casual-${i + 1}.jpeg`,
    category: 'casual' as const,
    description: 'Relaxed yet refined casual wear for the modern gentleman.',
    fabric: 'Breathable Linen-Cotton Blend',
    fit: 'Relaxed Fit',
    care: 'Machine Wash Cold',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Neutral Tones'],
    inStock: true,
  })),
  // African Culture Collection
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `african-${i + 1}`,
    name: `African Culture Design ${i + 1}`,
    price: 65000 + (i * 5000),
    image: `images/african-${i + 1}.jpeg`,
    category: 'african-culture' as const,
    description: 'A masterpiece representing the rich heritage and contemporary style of African culture.',
    fabric: 'Premium Cultural Fabric',
    fit: 'Classic Contemporary',
    care: 'Dry Clean Recommended',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Traditional Patterns'],
    inStock: true,
  })),
];

export const featuredProducts = allProducts.filter(p => 
  ['casual-1', 'casual-2', 'casual-3', 'casual-4', 'casual-5', 'casual-6'].includes(p.id)
);
